tail: True
log: True

debug: False

devices:
  red:    C4:33:9D:C8:FC:C3
  green:  E1:F3:FF:AD:A8:77
  blue:   C2:06:77:8A:B2:85
  coin:   CC:C1:08:69:C0:E1
  bare:   DC:21:3A:4D:3A:86

monitor: Granu.local